# Generated by Django 3.1.1 on 2020-10-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201001_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead0',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(),
        ),
    ]
